In [1]:
# импортируем наш любимый pandas
import pandas as pd

# загружаем данные
data = pd.read_csv('train_dataset_train.csv', sep=',')
data.head(10)

,id,ticket_id,ticket_type_nm,entrance_id,entrance_nm,station_id,station_nm,line_id,line_nm,pass_dttm,time_to_under,label
0,1,40BD89EC85646EFB69E283F39C298E60,Пропуск FacePay,2402,Лефортово БКЛ,11007,Лефортово,11,Большая кольцевая,2022-09-12 05:00:13,216.316667,8001
1,2,126727A96489CC976A8C08E5CEB00542,СК учащегося 30 дней,110,Войковская ( Южный ),2006,Войковская,2,Замоскворецкая,2022-09-12 05:00:54,648.183333,9011
2,3,D28CE6A9E0E5B6D213470A97CFF32485,БСК дружинника г.Москвы,110,Войковская ( Южный ),2006,Войковская,2,Замоскворецкая,2022-09-12 05:00:55,865.333333,7022
3,4,015DA44B523C062B5BFEFF3FB0E64B9E,30 дней,110,Войковская ( Южный ),2006,Войковская,2,Замоскворецкая,2022-09-12 05:01:13,1048.233333,2022
4,5,95B19C6F3A504727AC3EA56EB7E3E80F,КОШЕЛЕК,110,Войковская ( Южный ),2006,Войковская,2,Замоскворецкая,2022-09-12 05:02:55,965.600000,2017
5,6,A18692B5936C0B1689B8B3D904959534,СК студента 30 дней,103,Аэропорт ( Северный ),2003,Аэропорт,2,Замоскворецкая,2022-09-12 05:02:56,148.683333,11012
6,7,31CEE36AE183CF0EF7E4687993E8CC0E,Пропуск FacePay,2258,Косино (Первый),15001,Косино,15,Некрасовская,2022-09-12 05:02:59,192.150000,15001
7,8,EDFA01D6A6157E0716138DAA074ED974,Пропуск FacePay,2117,Котельники(Первый),7007,Котельники,7,Таганско-Краснопресненская,2022-09-12 05:03:00,229.400000,7014
8,9,532322AC5CDB5C0FE8C1F6308F9C2B7F,90 дней,103,Аэропорт ( Северный ),2003,Аэропорт,2,Замоскворецкая,2022-09-12 05:03:03,720.616667,5007
9,10,758C7FAEE0C3867835F6A16A0D05DCDD,СК студента 30 дней,107,Сокол ( Южн./Вост. ),2018,Сокол,2,Замоскворецкая,2022-09-12 05:04:31,329.433333,6018

In [2]:
data.describe()

,id,entrance_id,station_id,line_id,time_to_under,label
count,1.091021e+06,1.091021e+06,1.091021e+06,1.091021e+06,1.091021e+06,1.091021e+06
mean,5.455110e+05,8.581884e+02,8.601452e+03,8.590013e+00,5.104668e+02,7.723527e+03
std,3.149508e+05,9.003577e+02,1.247133e+04,1.247157e+01,2.328452e+02,1.167015e+04
min,1.000000e+00,2.000000e+01,1.002000e+03,1.000000e+00,3.001667e+01,1.002000e+03
25%,2.727560e+05,2.150000e+02,3.018000e+03,3.000000e+00,3.229500e+02,3.006000e+03
50%,5.455110e+05,3.370000e+02,7.009000e+03,7.000000e+00,5.686833e+02,6.013000e+03
75%,8.182660e+05,2.087000e+03,9.022000e+03,9.000000e+00,6.838833e+02,9.012000e+03
max,1.091021e+06,2.466000e+03,8.101600e+04,8.100000e+01,1.437417e+03,8.101600e+04

In [3]:
# какие колонки нужно удалить
columns_to_drop = [
    'id',
    'ticket_id',
    'entrance_id',
    'station_id',
    'line_id'
]
# эту колонку тоже, возможно, надо удалить
columns_to_drop.append('entrance_nm')
data = data.drop(columns=columns_to_drop)
data.head()

,ticket_type_nm,station_nm,line_nm,pass_dttm,time_to_under,label
0,Пропуск FacePay,Лефортово,Большая кольцевая,2022-09-12 05:00:13,216.316667,8001
1,СК учащегося 30 дней,Войковская,Замоскворецкая,2022-09-12 05:00:54,648.183333,9011
2,БСК дружинника г.Москвы,Войковская,Замоскворецкая,2022-09-12 05:00:55,865.333333,7022
3,30 дней,Войковская,Замоскворецкая,2022-09-12 05:01:13,1048.233333,2022
4,КОШЕЛЕК,Войковская,Замоскворецкая,2022-09-12 05:02:55,965.600000,2017

In [4]:
# посмотрим, как обстоит дело со значениями NULL
data.isnull().sum()

ticket_type_nm    0
station_nm        0
line_nm           0
pass_dttm         0
time_to_under     0
label             0
dtype: int64

In [5]:
# время и день захода на станцию тоже как-то влияет
data['pass_dttm'] = pd.to_datetime(data['pass_dttm'])

# время суток
data['hour'] = data['pass_dttm'].dt.hour
data['time_of_day'] = data['hour'].apply(
    lambda hour: 'day' if hour>=10 and hour<=16 else (
                 'night' if hour>=0 and hour<=4 else (
                 'morning' if hour>=4 and hour<=9 else 'evening')))

# выходной?
data['weekday'] = data['pass_dttm'].dt.weekday
data['is_weekend'] = data['weekday'].apply(
    lambda weekday: 1 if weekday>4 else 0)

data = data.drop(columns=['pass_dttm', 'hour', 'weekday'])

data.head(10)

,ticket_type_nm,station_nm,line_nm,time_to_under,label,time_of_day,is_weekend
0,Пропуск FacePay,Лефортово,Большая кольцевая,216.316667,8001,morning,0
1,СК учащегося 30 дней,Войковская,Замоскворецкая,648.183333,9011,morning,0
2,БСК дружинника г.Москвы,Войковская,Замоскворецкая,865.333333,7022,morning,0
3,30 дней,Войковская,Замоскворецкая,1048.233333,2022,morning,0
4,КОШЕЛЕК,Войковская,Замоскворецкая,965.600000,2017,morning,0
5,СК студента 30 дней,Аэропорт,Замоскворецкая,148.683333,11012,morning,0
6,Пропуск FacePay,Косино,Некрасовская,192.150000,15001,morning,0
7,Пропуск FacePay,Котельники,Таганско-Краснопресненская,229.400000,7014,morning,0
8,90 дней,Аэропорт,Замоскворецкая,720.616667,5007,morning,0
9,СК студента 30 дней,Сокол,Замоскворецкая,329.433333,6018,morning,0

In [6]:
# категориальные признаки
obj_feat = list(data.loc[:, data.dtypes=='object'].columns.values)
obj_feat

['ticket_type_nm', 'station_nm', 'line_nm', 'time_of_day']

In [7]:
for feature in obj_feat:
    data[feature] = pd.Series(data[feature], dtype='category')

In [8]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=['time_to_under', 'label'])
y = data['time_to_under']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

# далее разделим еще как бы
X_train, X_test, y_train, y_test = train_test_split(X_test, y_test, test_size=0.3)

In [9]:
import warnings
warnings.filterwarnings("ignore")

import lightgbm as lgb

from sklearn.model_selection import GridSearchCV

gbm = lgb.LGBMRegressor(objective='regression')

# наши параметры: num_leaves, n_estimators
params = {
    'num_leaves': range(1, 102, 10),
    'n_estimators': range(1, 102, 10)
}
grid = GridSearchCV(gbm, params, cv=5)
grid.fit(X_train, y_train)

gbm = grid.best_estimator_
print(grid.best_params_)

gbm.fit(X_train, y_train)

y_predict = gbm.predict(X_test, num_iteration=gbm.best_iteration_)

{'n_estimators': 51, 'num_leaves': 11}

In [10]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)
print(r2)

0.4677854455381253

In [11]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=['time_to_under', 'label'])
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

# разделим еще как бы
X_train, X_test, y_train, y_test = train_test_split(X_test, y_test, test_size=0.3)

In [12]:
gbm = lgb.LGBMClassifier(objective='multiclass', num_leaves=20, n_estimators=10)

gbm.fit(X_train, y_train)

y_predict = gbm.predict(X_test)

In [13]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_predict, average='micro')
print(recall)

0.0474764756201882

In [14]:
final = 0.5*r2 + 0.5*recall
print(final)

0.25763096057915674